config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/about',  to: 'static_pages#about'
  get  '/signup', to: 'users#new'
  get  '/login',  to: 'sessions#new'
  get  '/events',  to: 'events#index'
  post '/login',  to: 'sessions#create'
  post '/signup', to: 'users#create'
  delete '/logout', to: 'sessions#destroy'

  resources :events      
  resources :users
  resources :account_activations, only: [:edit]
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
    <%= link_to "Holmey Events", '#', id: "logo" %>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                    <li><%= link_to "Home", root_path %></li>
                    <li><%= link_to "About", about_path %></li>
                    <li><%= link_to "Events", events_path %></li>
                    <% if logged_in? %>
                        <li><%= link_to "Profile", current_user %></li>
                        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                        <li><%= link_to "Users", users_path %></li>
                        <li><%= link_to "Log out", logout_path, method: "delete" %></li>
                 <% else %>
                    <li><%= link_to "Log in", login_path %></li>
                <% end %>           
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Holmey Events</title>
      <%= csrf_meta_tags %>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

      <!--[if lt IE 9]>
        <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
        </script>
      <![endif]-->
  </head>

  <body>

    <%= render 'layouts/header' %>

    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>

        <footer class="footer">
          <small>
            Amazing app created by: Michael Holmes
          </small>
          <nav>
            <ul>
              <li><%= link_to "About", about_path %></li>
              <li><%= link_to "Events", events_path %></li>
              <li><%= link_to "Log in", login_path %></li>
            </ul> 
          </nav>
        </footer>
        <%= debug(params) if Rails.env.developtment? %>
      </div>
  </body>
</html>